### ISSUE TITLE
result from Collect() is empty with Youtube

### ISSUE THREAD

**Issue by LubinLemarchand** [voson-lab/SocialMediaLab#13]
Hi @timothyjgraham,
It appears i didn't pay enough attention last time.
So, when i run : 
```
> videoIDs <- c("W2GZFeYGU3s","mL27TAJGlWc")
> myData_youtube <- Authenticate("youtube", apiKey= myApiKey) %>% 
+   Collect(videoIDs = videoIDs,writeToFile=TRUE,verbose=TRUE)

Now scraping video number: 1 (out of 2 videos in total).....
Now scraping video number: 2 (out of 2 videos in total).....
Now cleaning and structuring data... please be patient...
YouTube data was written to current working directory, with filename:
mai_02_09_47_17_2016_CEST_YoutubeData.csv
Done! 
```
The result is empty. The names of the variables appear to be okay but both the file and the R object have 0 observations for 9 variables.

**Comment by timothyjgraham** [comment]
Hi @LubinLemarchand - I can't seem to reproduce the bug sorry. @rjackland - is it working for you?

Are you running on PC/Mac/Linux? What version of R are you using? Is your API key all set up correctly?

**Comment by LubinLemarchand** [comment]
Hi @timothyjgraham,
It's my bad. I assumed that there would be an error message if i was trying to authenticate with a wrong API key (like there is for twitter if i'm not mistaken).
