### ISSUE TITLE
Facebook authentication issue

### ISSUE THREAD

**Issue by cam59** [voson-lab/SocialMediaLab#5]
I'm having problems with initial Facebook authentication. I'll present screenshots here to make what I'm saying clear.

So I've created a developer app on Facebook and have my app id and secret. I run the code from the Social Media Lab reference manual....

![screen shot 2](https://cloud.githubusercontent.com/assets/16569628/12155276/715cc5a8-b518-11e5-8fb7-898fa30590f3.png)

So far so good...

Then I copy and paste the link into the site url on Facebook app settings like so...

![screen shot 3](https://cloud.githubusercontent.com/assets/16569628/12155288/7b6ecde8-b518-11e5-9ec9-fcd7a6bda28f.png)

I then 'save changes' in my Facebook Developer app settings and press a key to continue in RStudio. Then I get this..

![screen shot 4](https://cloud.githubusercontent.com/assets/16569628/12155300/80cca1ca-b518-11e5-81e4-a567e6ff486c.png)

Returning to RStudio, the screen freezes on this...

![screen shot 5](https://cloud.githubusercontent.com/assets/16569628/12155323/89c4afde-b518-11e5-8f73-d42d9fe0c5f3.png)

I get a similar result if I use my personal Mac rather than my work desktop, except the error message on my browser on my Mac says 'connection refused' rather than 'empty response'

I suspect that the problem might lie with Rfacebook somewhere. I used Rfacebook to authenticate instead and got something very similar...

I run the code from Rfacebook's reference manual like so...

![screen shot b1](https://cloud.githubusercontent.com/assets/16569628/12155329/8f23c7b2-b518-11e5-9f91-304c7b8619e8.png)

I copy and paste the local host into my site url...

![screen shot b2](https://cloud.githubusercontent.com/assets/16569628/12155337/9b737f26-b518-11e5-9c1d-7cab8a15b04e.png)

Then I get this error message...

![screen shot b4](https://cloud.githubusercontent.com/assets/16569628/12155342/a1502282-b518-11e5-8aab-bdcd57f8409e.png)

And Rstudio gets frozen in exactly the same way as when I use SocialMediaLab..

![screen shot b5](https://cloud.githubusercontent.com/assets/16569628/12155351/a4acf766-b518-11e5-9377-e33765f39c08.png)

I hope you can help. Apologies if it turns out to be something pretty basic. I'm very much a beginner when it comes to Facebook developer apps!

I should point out that when I use R through my own Mac rather than EC2, It appears at first that I can authenticate but then the access token I create is not recognized. Here is a screenshot...

![screenshot 2016-01-06 15 19 02](https://cloud.githubusercontent.com/assets/16569628/12155354/a98f18c2-b518-11e5-8233-05c399169aa1.png)

**Comment by rjackland** [comment]
Hi,

One thing: I know it says "copy and paste into site URL on Facebook App Settings" and this is what you did above, but when I use SML I don't recall doing what you are apparently doing.  Instead, I just press enter and then the browser opens up and I authenticate with Facebook.

So perhaps you can try that?

It would be best if you can initially test on your local machine (as you did above) rather than on your EC2 instance.

The problem I had with running SML on a virtual machine was that the browser would be automatically opening up on the host, not the guest, and so the authentication token was not being saved to the VM and hence SML couldn't access it.  From memory, the way I solved this was a bit of a hack: copying the authentication token from the host machine to the guest machine.

Rob

**Comment by cam59** [comment]
Dear Rob,

Thank you very much! It looks like I’m good now. Rfacebook wasn’t working outside of EC2 either, so I didn’t think that would solve the problem, but it appears that it did…

I’ll let you know if there are any further problems and will give you a shout when the chapters are complete too.

Best

Charlie

PS – YouTube authentication is working just fine.

**Comment by timothyjgraham** [comment]
I am closing this now, as it appears to be fixed.

**Comment by cam59** [comment]
Yes it is fixed. Sorry I thought I'd closed it myself

Sent from my iPad

On 6 Feb 2016, at 5:55 pm, Tim Graham <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #5<https://github.com/voson-lab/SocialMediaLab/issues/5>.

-

**Comment by timothyjgraham** [comment]
@cam59 No worries! Glad to hear it is all sorted now.
